### ISSUE TITLE
Dev setup for changes spanning both the Station UI and Module UI

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/filecoin-station#24]
To make our life easier when making changes in all three components (Shell, Module backend, Module frontend at the same time, e.g. when troubleshooting a bug: we need to set up a dev env that links dev versions of all three components together. Ideally, the Shell running in a Dev mode should be rendering the Module frontend served by a dev-server with live reloading, so that after every change in the Module frontend we don’t have to rebuild both Module frontend & backend and restart the Module backend.

For example, we can set up a dev proxy server to route requests to Module WebUI assets to the WebUI dev server and Module backend requests to the module backend process.

**Tasks**

- [ ] Propose the setup
- [ ] Implement the necessary helper scripts
- [ ] Update docs in [DEVELOPING.md](https://github.com/filecoin-project/filecoin-station/blob/main/docs/DEVELOPING.md)

**Comment by bajtos** [comment]
As part of our recent pivot, we decided that Station should provide a station-wide dashboard. We don't intend to provide module-level dashboards in the foreseeable future. Therefore we don't need to make changes across both Station UI and Module UI.

I am closing this task as "not planned".
